In [1]:
import pandas as pd 
pd.__version__

'1.4.2'

In [2]:
business_json_path = '/Users/hannahokeeffe/Documents/yelp_dataset/yelp_academic_dataset_business.json'
business = pd.read_json(business_json_path, lines=True)
print(business.shape)
business.head()

(150346, 14)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,13,1,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food","{'Wednesday': '14:0-22:0', 'Thursday': '16:0-2..."

In [3]:
#Only keep businesses that are still open in the dataset
business.is_open.value_counts()

1    119698
0     30648
Name: is_open, dtype: int64

In [4]:
df_business = business[business['is_open']==1].drop(['hours', 'is_open', 'review_count'], axis=1)
print(df_business.shape)
df_business.head()

(119698, 11)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,attributes,categories
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,PA,18054,40.338183,-75.471659,4.5,"{'BusinessAcceptsCreditCards': 'True', 'Wheelc...","Brewpubs, Breweries, Food"
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea..."
6,n_0UpQx1hsNbnPUSlodU8w,Famous Footwear,"8522 Eager Road, Dierbergs Brentwood Point",Brentwood,MO,63144,38.627695,-90.340465,2.5,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Sporting Goods, Fashion, Shoe Stores, Shopping..."

In [5]:
# Create one row for each series that contain comma-separated items
df_explode = df_business.assign(categories = df_business.categories.str.split(', ')).explode('categories')
df_explode.sample(3)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,attributes,categories
54678,l4sOZLkxQekdzryZGdtvKQ,Holiday Inn Express Indianapolis - Fishers,9791 N By Ne Blvd,Fishers,IN,46037,39.929709,-86.023978,2.5,"{'RestaurantsPriceRange2': '2', 'WiFi': 'u'fre...",Hotels & Travel
44223,5H54eU9FBQmUowDf1XpHLA,The Garden Medical Spa,"100 NJ-73, Ste 1",Voorhees Township,NJ,08043,39.826600,-74.927042,4.0,"{'WheelchairAccessible': 'True', 'BusinessPark...",Medical Spas
106596,6_LnAQQ0-mml8YgpfRjGuA,Saad's Halal Restaurant,4500 Walnut St,Philadelphia,PA,19139,39.954963,-75.211851,4.5,"{'BusinessAcceptsCreditCards': 'False', 'WiFi'...",Desserts

In [6]:
#Split the businesses by category
print('Total number of categories:', len(df_explode.categories.value_counts()))
print('Top 10 categories:')
df_explode.categories.value_counts()[:10]

Total number of categories: 1302
Top 10 categories:

Restaurants                  34987
Food                         20419
Shopping                     20186
Home Services                13322
Beauty & Spas                12263
Health & Medical             11046
Local Services               10138
Automotive                    9879
Nightlife                     8379
Event Planning & Services     8173
Name: categories, dtype: int64

In [7]:
#Find all categories under Fast Food 
df_explode[df_explode['categories'].str.contains('Fast Food', case=True, na=False)].categories.value_counts()

Fast Food    5516
Name: categories, dtype: int64

In [9]:
business_Fast_Food= df_business[df_business['categories'].str.contains(
                         'Fast Food', case=False, na=False)]
print(business_Fast_Food.shape)
business_Fast_Food.head()

(5516, 11)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,attributes,categories
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea..."
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,..."
97,knQ4vIgx-r85kjlWVVjcpQ,Silver and Blue Outfitters,5191 Meadowood Mall Cir,Reno,NV,89502,39.476518,-119.784037,4.5,"{'BikeParking': 'True', 'WiFi': 'u'no'', 'Dogs...","Sporting Goods, Sports Wear, Fashion, Restaura..."
122,VZzivJEbmHItOxNXJB3SpA,Subway,"330 Franklin Rd, Ste 900-d",Brentwood,TN,37027,36.026363,-86.789473,2.5,"{'BusinessParking': '{'garage': False, 'street...","Sandwiches, Fast Food, Restaurants"
153,aNtKyc2rr-uK5cqzY9TVQQ,Chipotle Mexican Grill,10160 Ulmerton Rd,Largo,FL,33771,27.894167,-82.779866,3.0,"{'RestaurantsPriceRange2': '1', 'Caters': 'Tru...","Mexican, Fast Food, Restaurants"

In [10]:
#Get the reviews
review_json_path = '/Users/hannahokeeffe/Documents/yelp_dataset/yelp_academic_dataset_review.json'

In [11]:
#Use pandas to load large data by segmenting the file
size = 1000000
review = pd.read_json(review_json_path, lines=True,
                      # identifying the data type of each column can reduce memory usage
                      dtype={'review_id':str,'user_id':str,'business_id':str,'stars':int,
                             'date':str,'text':str,'useful':int,'funny':int,'cool':int},
                      chunksize=size)

In [12]:
#Read one chunk of data at a time
chunk_list = []
for chunk in review:
    # Drop columns that aren't needed
    chunk = chunk.drop(['review_id','useful','funny','cool'], axis=1)
    # Renaming column name to avoid conflict with business overall star rating
    chunk = chunk.rename(columns={'stars': 'review_stars'})
    # Inner merge with edited business file so only reviews related to Fast Food remain
    chunk_merged = pd.merge(business_Fast_Food, chunk, on='business_id', how='inner')
    # Show feedback on progress
    print(f"{chunk_merged.shape[0]} out of {size:,} related reviews")
    chunk_list.append(chunk_merged)
    
# After trimming down the review file, concatenate all relevant data back to one dataframe
df = pd.concat(chunk_list, ignore_index=True, join='outer', axis=0)
print(df.shape)
df.sample(3)

25746 out of 1,000,000 related reviews
27231 out of 1,000,000 related reviews
26610 out of 1,000,000 related reviews
28672 out of 1,000,000 related reviews
30069 out of 1,000,000 related reviews
31097 out of 1,000,000 related reviews
34735 out of 1,000,000 related reviews
(204160, 15)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,attributes,categories,user_id,review_stars,text,date
116214,PSy-g99cUhi0FRyTKmPRQg,Taco Bell,6560 N. Linder Road,Eagle,ID,83616,43.664327,-116.413251,1.5,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Tex-Mex, Restaurants, Fast Food, Breakfast & B...",VX10_gAHGNkbaKGmZA0t8A,2,I thought I'd give this location another shot ...,2018-12-02 01:10:35
110872,WiU5xLpdyCcDNZixMNf4kQ,Arby's,25 S Franklin Rd,Indianapolis,IN,46219,39.772414,-86.025830,2.5,"{'RestaurantsTakeOut': 'True', 'HasTV': 'True'...","Sandwiches, Fast Food, Restaurants",9hIZfdgtWoVAg8eMtjiqkA,1,You are the reason I don't eat Arby's anywhere...,2020-02-19 02:42:20
152265,HrEIQSum1FKPJoXlI9UU_w,Chick-fil-A,4 West Rd,Newtown,PA,18940,40.235370,-74.947250,3.0,"{'BikeParking': 'True', 'Caters': 'True', 'Out...","Fast Food, Desserts, Restaurants, Food, Catere...",DO7IB9G2U4BPllAVsjgzzw,1,Day 2 still out of Peach Shakes. Not good at a...,2014-08-16 15:21:06

In [13]:
#Convert the new data fram into a csv file creating more concise dataset
#Dataset further edited in csv form to remove further irrelevant information
df.to_csv("yelp_reviews_Fast_Food_categories.csv", index=False)